spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/g2g_calculator
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
    default-schema: wow
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 100
server:
  port: 8080
g2g:
  force-update: ${G2G_FORCE_UPDATE:false}
  scraping-interval: ${G2G_SCRAPING_INTERVAL:60}
  api-key: YOUR_API_KEY