spring:
  data:
    rest:
      max-page-size: 40000
      default-page-size: 100
    web:
      pageable:
        max-page-size: 40000
        default-page-size: 100
  task:
    scheduling:
      pool:
        size: 4
  application:
    name: EconOMatic
  datasource:
    url: ${DATABASE_URL}
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never
    include-message: never
economatic:
  update-on-startup: ${UPDATE_ON_STARTUP:true}
  population:
    update-rate: ${POPULATION_UPDATE_RATE:1}
  item-price:
    update-rate: ${ITEM_PRICE_UPDATE_RATE:3}
  gold-price:
    update-rate: ${GOLD_PRICE_UPDATE_RATE:60}
