
spring:
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  task:
    scheduling:
      pool:
        size: 3
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  mustache:
    check-template-location: false
  application:
    name: PricePal
  datasource:
    url: jdbc:postgresql://localhost:5433/g2g_calculator?currentSchema=wow
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
    enabled: true
    default-schema: wow
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never
    include-message: never


logging:
  level:
   org:
    atmosphere: warn
vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application,com.vaadin,org.vaadin,com.github.appreciated.apexcharts,com.thoroldvix.pricepal.ui
  exclude-urls: /swagger-ui/**