spring:
  data:
    web:
      pageable:
        max-page-size: 40000
        default-page-size: 100
  task:
    scheduling:
      pool:
        size: 4
  application:
    name: PricePal
  datasource:
    url: jdbc:postgresql://localhost:5433/pricepal
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
    enabled: true
    contexts: dev
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never
    include-message: never