spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/g2g_calculator
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
    default-schema: wow
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080